export enum AppRoutePage {
  Home = '',
  Auth = 'auth',
  AuthLogin = 'auth/login',
  AuthRegister = 'auth/register',
  ProfileEditProfile = 'perfil/editar-perfil',
  Login = 'login',
  Register = 'register',
  Profile = 'profile',
  Article = 'article',
  PublishArticle = 'publish-article',
  EditArticle = 'edit-article',
  MyArticles = 'my-articles',
  UserManagement = 'management/users',
  RoleManagement = 'roles',
}
